version: '3'
services:
    lumi-rest-server:
        image: 'milliweb/lumi_rest_server:1.1.0'
        build: .
        ports:
            - '8080:8080'
        security_opt:
            - 'apparmor:unconfined'
        volumes:
            - './h5p/content:/usr/src/app/h5p/content'
            - './h5p/libraries:/usr/src/app/h5p/libraries'
